export const PARSE_DATA_LOADED = "PARSE_DATA_LOADED";
export const CONTAINS_DATA_LOADED = "CONTAINS_DATA_LOADED";
export const LOADING_DATA = "LOADING_DATA";

export const SERVER_ERROR = "SERVER_ERROR";